// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grad_lambda_cpp
arma::Mat<double> grad_lambda_cpp(double k, double ni, arma::vec Yi, arma::mat Lambda, arma::mat Sigma_u, arma::mat Theta, arma::mat Psi, arma::mat nonzero);
RcppExport SEXP _mrabbott_grad_lambda_cpp(SEXP kSEXP, SEXP niSEXP, SEXP YiSEXP, SEXP LambdaSEXP, SEXP Sigma_uSEXP, SEXP ThetaSEXP, SEXP PsiSEXP, SEXP nonzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type ni(niSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yi(YiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_u(Sigma_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nonzero(nonzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_lambda_cpp(k, ni, Yi, Lambda, Sigma_u, Theta, Psi, nonzero));
    return rcpp_result_gen;
END_RCPP
}
// grad_sigma_u_cpp
arma::Mat<double> grad_sigma_u_cpp(double k, double ni, arma::vec Yi, arma::mat Lambda, arma::mat Sigma_u, arma::mat Theta, arma::mat Psi, arma::mat nonzero);
RcppExport SEXP _mrabbott_grad_sigma_u_cpp(SEXP kSEXP, SEXP niSEXP, SEXP YiSEXP, SEXP LambdaSEXP, SEXP Sigma_uSEXP, SEXP ThetaSEXP, SEXP PsiSEXP, SEXP nonzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type ni(niSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yi(YiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_u(Sigma_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nonzero(nonzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_sigma_u_cpp(k, ni, Yi, Lambda, Sigma_u, Theta, Psi, nonzero));
    return rcpp_result_gen;
END_RCPP
}
// grad_sigma_e_cpp
arma::Mat<double> grad_sigma_e_cpp(double k, double ni, arma::vec Yi, arma::mat Lambda, arma::mat Sigma_u, arma::mat Theta, arma::mat Psi, arma::mat nonzero);
RcppExport SEXP _mrabbott_grad_sigma_e_cpp(SEXP kSEXP, SEXP niSEXP, SEXP YiSEXP, SEXP LambdaSEXP, SEXP Sigma_uSEXP, SEXP ThetaSEXP, SEXP PsiSEXP, SEXP nonzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type ni(niSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yi(YiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_u(Sigma_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nonzero(nonzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_sigma_e_cpp(k, ni, Yi, Lambda, Sigma_u, Theta, Psi, nonzero));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrabbott_grad_lambda_cpp", (DL_FUNC) &_mrabbott_grad_lambda_cpp, 8},
    {"_mrabbott_grad_sigma_u_cpp", (DL_FUNC) &_mrabbott_grad_sigma_u_cpp, 8},
    {"_mrabbott_grad_sigma_e_cpp", (DL_FUNC) &_mrabbott_grad_sigma_e_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrabbott(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
